version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: flywya_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
